# Generated by Django 4.1.7 on 2023-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('fam', models.CharField(max_length=222)),
                ('yosh', models.IntegerField()),
            ],
        ),
    ]
